Lab01 (Lazy)
alefedor/java-spring-2018 pull request #1
Opened 2018-02-28 19:59 UTC by alefedor

2018-03-07 06:53 UTC, jzuken requested changes

2018-03-07 06:53 UTC, jzuken commented on script.sh
> +    ./gradlew build --stacktrace
./gradlew test тогда уж

2018-03-07 06:53 UTC, jzuken commented on Lab01_1/src/main/java/ru/spbau/fedorov/algo/LazyFactory.java
> +            private Optional<T> result;
volatile не помешает

2018-03-07 09:08 UTC, alefedor commented on Lab01_1/src/main/java/ru/spbau/fedorov/algo/LazyFactory.java
> +            private Optional<T> result;
Я добавил, но все равно не очень понятно, как без него может стать плохо. Проверка на null проводится внутри syncronized {}, а когда функция доходит до return, там уже result не null и больше никогда не поменяется. Из-за volatile же происходит замедление

2018-03-12 14:49 UTC, jzuken commented on Lab01_1/src/main/java/ru/spbau/fedorov/algo/LazyFactory.java
> +            private Optional<T> result;
вот [тут](https://ru.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0_%D1%81_%D0%B4%D0%B2%D0%BE%D0%B9%D0%BD%D0%BE%D0%B9_%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%BE%D0%B9#%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80_%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F_%D0%B2_Java) написано, что может пойти не так. случаи редкие, но мало ли, лучше привыкать писать правильно

2018-03-12 14:49 UTC, jzuken commented
ок, можно мерджить. и мне доступ дать на запись было бы неплохо

2018-03-12 14:57 UTC, merged