Lab02 (JavaFX)
alefedor/java-spring-2018 pull request #3
Opened 2018-03-14 21:34 UTC by alefedor

2018-04-02 07:15 UTC, jzuken requested changes

2018-04-02 07:15 UTC, jzuken commented on Lab02/src/main/java/ru/spbau/fedorov/tictactoe/Controller.java
> +            onGameEnd(result);
ну вообще model.getGameResult() возвращает nullable, а onGameEnd() хочет нечто notnull

2018-04-02 07:15 UTC, jzuken commented on Lab02/src/main/java/ru/spbau/fedorov/tictactoe/Controller.java
> +        if (id.equals("easyBot")) {
хотелось бы избежать сравнения со строковыми значениями. это крайне ненадёжный механизм, мало ли кто где опечатается

2018-04-02 07:15 UTC, jzuken commented on Lab02/src/main/java/ru/spbau/fedorov/tictactoe/statistics/GameInfo.java
> +        Win,
как-то не очень по стайлгайду они называются у вас

2018-04-02 07:15 UTC, jzuken commented on Lab02/src/main/java/ru/spbau/fedorov/tictactoe/logic/Model.java
> +    private Sign[][] board = new Sign[3][3];
магические константы это грустно

2018-04-02 07:15 UTC, jzuken commented on Lab02/src/main/java/ru/spbau/fedorov/tictactoe/logic/Model.java
> +        N
empty?

2018-04-02 07:15 UTC, jzuken commented on Lab02/src/main/java/ru/spbau/fedorov/tictactoe/logic/Model.java
> +        for (int i = 0; i < 3; i++) {
предлагаю разбить на мелкие функции с понятными именами

2018-04-25 09:12 UTC, jzuken requested changes

2018-04-25 09:12 UTC, jzuken commented on Lab02/src/main/java/ru/spbau/fedorov/tictactoe/Controller.java
> +                e.printStackTrace();
в единственном месте, где это исключение бросается, оно тупо игнорируется. мне кажется, что-то здесь не так :)

2018-04-25 11:24 UTC, alefedor commented on Lab02/src/main/java/ru/spbau/fedorov/tictactoe/Controller.java
> +                e.printStackTrace();
Ну потому что в этом единственном месте я перед вызовом делаю проверку помощью .gameEnded(), что гарантирует, что исключение не бросится.

2018-04-26 06:30 UTC, jzuken commented on Lab02/src/main/java/ru/spbau/fedorov/tictactoe/Controller.java
> +                e.printStackTrace();
а зачем нам тогда это исключение? или проверка там? подобная схема выглядит абсурдно -- исключение как бы есть, но оно никогда не бросится

2018-04-26 06:45 UTC, alefedor commented on Lab02/src/main/java/ru/spbau/fedorov/tictactoe/Controller.java
> +                e.printStackTrace();
Ну вроде причины для использования исключения стандартны: когда нас спросили про результат игры, а игра еще не закончилась, непонятно, что возвращать, поэтому бросается исключение.

2018-05-08 19:36 UTC, alefedor commented on Lab02/src/main/java/ru/spbau/fedorov/tictactoe/Controller.java
> +                e.printStackTrace();
Добавил в javadoc информацию про гарантию и теперь в этом месте кидаю exception.

2018-05-30 11:37 UTC, merged