Added Lab03
alefedor/java-spring-2018 pull request #5
Opened 2018-05-02 18:33 UTC by alefedor

2018-05-13 14:08 UTC, jzuken requested changes

2018-05-13 14:08 UTC, jzuken commented on Lab03/src/main/java/ru/spbau/fedorov/algo/client/FTPClient.java
> +public class FTPClient {
для сервера есть main(), а для клиента нет? а как его запустить и проверить работу тогда?

2018-05-13 14:08 UTC, jzuken commented on Lab03/src/main/java/ru/spbau/fedorov/algo/server/FTPServer.java
> +    private static final int LIST = 1;
это как-то стоит переиспользовать между клиентом и сервером, как мне кажется

2018-05-13 14:22 UTC, alefedor commented on Lab03/src/main/java/ru/spbau/fedorov/algo/client/FTPClient.java
> +public class FTPClient {
Есть GUI, в котором все запросы клиента и кнопочка "Run server"

2018-05-14 03:57 UTC, jzuken commented on Lab03/src/main/java/ru/spbau/fedorov/algo/client/FTPClient.java
> +public class FTPClient {
gui это другая задача

2018-05-30 11:55 UTC, jzuken commented
запускаю сервер, запускаю клиент и тишина. пишу команды, и снова тишина. я что-то делаю не так?

2018-05-30 15:49 UTC, alefedor commented
Сорри, там буфер не сбрасывался, поэтому ничего не выводилось (хотя команда exit работала корректно, а про другие команды server сообщал, что был такой запрос)

2018-06-14 08:42 UTC, jzuken commented
а тут конфликт с мастером

2018-06-14 08:43 UTC, jzuken commented
get src
Fail in IO
java.io.FileNotFoundException: src (Отказано в доступе)

падать с исключением как-то не круто

2018-06-14 08:45 UTC, jzuken commented
list .
List files in path .
Directory .gradle
Directory .idea
Directory build
File build.gradle
Directory gradle
File gradlew
File gradlew.bat
File Lab03.iml
File settings.gradle
Directory src

get gradlew
Getting file from path gradlew
No such file

я опять что-то делаю не так? :)

2018-06-14 11:20 UTC, alefedor commented
Конфликт исправил.

Usage: "get/list <path : String> or exit"
Т.е. путь к файлу нужно прописывать
Это уже в GUI можно не прописывать, а только выделить имя и скачать

Падать с исключением выдавая сообщение лучше, чем просто падать.
Здесь скорее всего проблема в том, что серверу прав не хватило?
Т.к. директории обрабатываются корректно

Мне не очень хочется все это исправлять, учитывая, что дедлайн на проверку (зачетная неделя) уже закончился, и теперь сессия

Если не максимум, то поставьте пожалуйста хоть что-то

2018-06-14 12:01 UTC, jzuken commented
мне сказали, что дедлайн на проверку конец сессии

2018-06-14 12:03 UTC, jzuken commented
ок, поставил 9 баллов

2018-06-14 12:04 UTC, alefedor commented
Ок

2018-11-26 14:15 UTC, closed without merging